---
title: "R Notebook"
output: html_notebook
author: "Manuel Tognon, Simone Avesani"
---

## ES1

Given a tsv file with 10 rows and 6 columns
```{bash}
  cat "myFile.tsv"| head -n 5 | cut -f 6 | tail -n 4 

```
a) returns an error
b) prints the last 4 rows of the file
c) prints the first 4 rows of the file
d) prints the last 4 values of the sixth column
e) prints the second the third, the fourth and the fifth values of the sixth column (X)



## ES2
Imagine to have gff file, you want to extract the rows with data related to the chromosome.
Which bash command would you use?

a) grep (X)
b) tar -xzf
c) cat
d) find
e) cut -f2 | grep  



## ES3

Assume a tsv file with 5 columns and 100 rows. 
What is the result of the following command applied to the file:

```{bash}
sort -rk4

```
a) sort the rows in asceding order according to value in column 3
b) sort the rows in descending order according to value in column 3 (X)
c) sort only the values in column 3 in descending order
d) print only the third column 
e) sort all the files containined in the directory containing the number 3 in the name in descending order
 

## ES4

Writing a file, which is the difference between > and >> ?

a) there is not difference
b) > append the stdoutput at the end of the file, >> write on the std error
c) > append the stdoutput at the end of the file, >> redirect the std output to the file deleting the current file content
d) > redirect the std output on the file deleting the current content, >> redirect the file content to the standard input
e) > redirect the std output to the file deleting the current file content, >> append the stdoutput at the end of the file (X)


## ES5

Consider the tsv file "my_dataset.tsv". 
Create a new file called "my_dataset_new.tsv" containing only the Sepal.Length, Sepal.Width and Species columns of "setosa" species sorted in descending order of Sepal.Length

```{bash}

cat "my_dataset.tsv" | grep "setosa" | cut -f 2,3,6  | sort -rk 1> "my_dataset_new.tsv"
 
```


## ES6

Create a new directory called "my_dir", then rename it as "my_dir2", create inside "my_dir2" atxt file called "my_file.txt" and write to "my_file.txt" a numeric sequence from 1:10



## ES7

Given the gff file, create a file for each strand and make them as valid GFF3 files


## ES8 
Create a function which reads a gff3 file and prints the total number of features contained in the gff file, the number of features by chromosome, the number of features belonging to the forward strand (+) and to reverse strand (-), compute the average score by chromosome (Hint: the score is in the sixth column, and the strand is in the seven column)

```{bash}



```

